### ISSUE TITLE
Server exited with error code 10.

### ISSUE THREAD

**Issue by Graf-Koks** [jjolano/openps3ftp#10]
Using Version 4.4 (Experimental Release 4) on 4.81.2 and 4.82.2 rex package installation seems to be ok, but it fails when launching the server: Server exited with error code 10.

**Comment by jjolano** [comment]
Try this pkg. I briefly tested it to see if it will launch and it seemed to work for me.
[UP0001-NPXS91337_00-0000000000000000.zip](https://github.com/jjolano/openps3ftp/files/1889281/UP0001-NPXS91337_00-0000000000000000.zip)

**Comment by Graf-Koks** [comment]
works - thanks a lot
