### ISSUE TITLE
Plugin? 

### ISSUE THREAD

**Issue by metal-velcro** [jjolano/openps3ftp#4]
Any chance of making this a stand-alone plugin I've noticed with the recent changes it is much faster

**Comment by jjolano** [comment]
Standalone plugin? Do you mean like a sprx kind of thing?

That's been on my mind since version 1.. I don't know how to do that but maybe I should learn!

**Comment by aldostools** [comment]
To create your own plugin version, I suggest you try modifying the code of webMAN or webMAN MOD:
Both links include the full source code:
http://deanbg.com/webMAN_1.46.zip
http://github.com/aldostools/webMAN-MOD

Both projects include a modified version of OpenPS3FTP and extended features that I'd like to suggest you to include in your standalone version.

The following are a list of extended FTP features included in webMAN MOD:
- NTFS support
- Recursive folder delete
- Filter content in directory listing (e.g. list *.txt)
- Extended custom commands:
  SITE FLASH  -> Turns on/off /dev_blind
  SITE NTFS  -> Refresh mount of NTFS devices
  SITE INSTALL <file> -> Start install PKG on XMB
  SITE EXTGD <ON/OFF> -> Turns on/off redirection of /dev_hdd0/game to USB
  SITE MAPTO <path> ->Redirect current path to virtual path
  SITE FIX <path> -> Fix eboot/sprx/iso
  SITE UMOUNT -> Unmount /dev_bdvd
  SITE COPY <path> -> Copy path to "clipboard"
  SITE PASTE <path>-> Copy the files "stored" in clipboard to the specified path
  SITE CHMOD 777 <file> -> Change fiile permissions
  SITE SHUTDOWN -> Shutdown console
  SITE RESTART -> Restart console
